In [1]:
import torch
from torch import tensor

In [2]:
point = torch.tensor([[[.1, .2, .3, .4], [.5, .6, .7, .8], [.9, 1.0, 1.1, 1.2]], [[1.3, 1.4, 1.5, 1.6], [1.7, 1.8, 1.9, 2.0], [2.1, 2.2, 2.3, 2.5]]])
point_t = point.transpose(0, 2)

In [3]:
point.stride(), point_t.stride()

((12, 4, 1), (1, 4, 12))

In [4]:
point

tensor([[[0.1000, 0.2000, 0.3000, 0.4000],
         [0.5000, 0.6000, 0.7000, 0.8000],
         [0.9000, 1.0000, 1.1000, 1.2000]],

        [[1.3000, 1.4000, 1.5000, 1.6000],
         [1.7000, 1.8000, 1.9000, 2.0000],
         [2.1000, 2.2000, 2.3000, 2.5000]]])

In [5]:
point.is_contiguous()

True

In [6]:
point_t.is_contiguous()

False

In [7]:
point_tc = point_t.contiguous()

In [8]:
point_tc.is_contiguous()

True

In [9]:
point.is_contiguous()

True

In [10]:
point.stride(), point_t.stride(), point_tc.stride()

((12, 4, 1), (1, 4, 12), (6, 2, 1))

In [11]:
point[0][0][0] = 10.0


In [12]:
point[0][0][0], point_t[0][0][0], point_tc[0][0][0]  # point_tc not changed -> memory values are copied to another memory

(tensor(10.), tensor(10.), tensor(0.1000))

In [13]:
id(point.untyped_storage()) == id(point_tc.untyped_storage())  # do not use storage. it will be deprecated

False

In [14]:
id(point.untyped_storage()) == id(point_t.untyped_storage())

True

In [15]:
if torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")
print("device:", device)
point_gpu = torch.tensor([[1.0, 2.0], [3.0, 4.0]], device=device)

device: mps


In [16]:
point_gpu = 2 * point_gpu

In [17]:
point_gpu

tensor([[2., 4.],
        [6., 8.]], device='mps:0')

In [18]:
point_cpu = point_gpu.to(device='cpu')

In [19]:
point_cpu

tensor([[2., 4.],
        [6., 8.]])

In [20]:
import h5py

In [32]:
with h5py.File('../resources/point.hdf5', 'w') as f:
    dset = f.create_dataset('point', data=point.numpy())

In [34]:
with h5py.File('../resources/point.hdf5', 'r') as f:
    dset = f['point']
    print(dset[:])
    loaded_point = torch.from_numpy(dset[:])

[[[10.   0.2  0.3  0.4]
  [ 0.5  0.6  0.7  0.8]
  [ 0.9  1.   1.1  1.2]]

 [[ 1.3  1.4  1.5  1.6]
  [ 1.7  1.8  1.9  2. ]
  [ 2.1  2.2  2.3  2.5]]]


In [35]:
loaded_point

tensor([[[10.0000,  0.2000,  0.3000,  0.4000],
         [ 0.5000,  0.6000,  0.7000,  0.8000],
         [ 0.9000,  1.0000,  1.1000,  1.2000]],

        [[ 1.3000,  1.4000,  1.5000,  1.6000],
         [ 1.7000,  1.8000,  1.9000,  2.0000],
         [ 2.1000,  2.2000,  2.3000,  2.5000]]])